beamer:
    latexmk -pdf hdnum-tutorial-beamer.tex 

article:
    latexmk -pdf hdnum-tutorial-article.tex 

clean:
	rm *.bbl *.blg *.dvi *.aux *.idx *.log *.lof *.toc *.lot *.ind *.ilg *.snm *.nav *.out *.vrb *.fls *_latexmk *.pdf
