include ../../make.def
HDNUMPATH  = ../..

all: vectores01 vectores02 vectores03
vectores01: vectores01.cc
	$(CC) $(CCFLAGS) -o $@ $^ $(LFLAGS)
vectores02: vectores02.cc
	$(CC) $(CCFLAGS) -o $@ $^ $(LFLAGS)
vectores03: vectores03.cc
	$(CC) $(CCFLAGS) -o $@ $^ $(LFLAGS)